export const currencies = {
  GBP: { symbol: '£', name: 'British Pound' },
  AUD: { symbol: '$', name: 'Australian Dollar' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev' },
  BRL: { symbol: 'R$', name: 'Brazilian Real' },
  CAD: { symbol: '$', name: 'Canadian Dollar' },
  CHF: { symbol: 'Fr', name: 'Swiss Franc' },
  CNY: { symbol: '¥', name: 'Chinese Yuan Renminbi' },
  CZK: { symbol: 'Kč', name: 'Czech Republic Koruna' },
  DKK: { symbol: 'kr', name: 'Danish Krone' },
  HKD: { symbol: '$', name: 'Hong Kong Dollar' },
  HRK: { symbol: 'kn', name: 'Croatian Kuna' },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah' },
  ILS: { symbol: '₪', name: 'Israeli New Shekel' },
  INR: { symbol: '₹', name: 'Indian Rupee' },
  JPY: { symbol: '¥', name: 'Japanese Yen' },
  KRW: { symbol: '₩', name: 'South Korean Won' },
  MXN: { symbol: '$', name: 'Mexican Peso' },
  MYR: { symbol: 'RM', name: 'Malaysian Ringgit' },
  NOK: { symbol: 'kr', name: 'Norwegian Krone' },
  NZD: { symbol: '$', name: 'New Zealand Dollar' },
  PHP: { symbol: '₱', name: 'Philippine Peso' },
  PLN: { symbol: 'zł', name: 'Polish Złoty' },
  RON: { symbol: 'lei', name: 'Romanian New Leu' },
  RUB: { symbol: '₽', name: 'Russian Ruble' },
  SEK: { symbol: 'kr', name: 'Swedish Krona' },
  SGD: { symbol: '$', name: 'Singapore Dollar' },
  THB: { symbol: '฿', name: 'Thai Baht' },
  TRY: { symbol: 'TRY', name: 'Turkish Lira' },
  USD: { symbol: '$', name: 'US Dollar' },
  ZAR: { symbol: 'R', name: 'South African Rand' },
  EUR: { symbol: '€', name: 'Euro' }
}
