export const currencies = {
  GBP: { symbol: '£', name: 'British Pound' },
  AUD: { symbol: '$', name: 'Australian Dollar' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev', from: '2000-07-19' },
  BRL: { symbol: 'R$', name: 'Brazilian Real', from: '2008-01-02' },
  CAD: { symbol: '$', name: 'Canadian Dollar' },
  CHF: { symbol: 'Fr', name: 'Swiss Franc' },
  CNY: { symbol: '¥', name: 'Chinese Yuan Renminbi', from: '2005-04-01' },
  CZK: { symbol: 'Kč', name: 'Czech Republic Koruna' },
  DKK: { symbol: 'kr', name: 'Danish Krone' },
  HKD: { symbol: '$', name: 'Hong Kong Dollar' },
  HRK: { symbol: 'kn', name: 'Croatian Kuna', from: '2005-04-01' },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah', from: '2005-04-01' },
  ILS: { symbol: '₪', name: 'Israeli New Shekel', from: '2011-01-03' },
  INR: { symbol: '₹', name: 'Indian Rupee', from: '2009--01-02' },
  JPY: { symbol: '¥', name: 'Japanese Yen' },
  KRW: { symbol: '₩', name: 'South Korean Won' },
  MXN: { symbol: '$', name: 'Mexican Peso', from: '2008-01-02' },
  MYR: { symbol: 'RM', name: 'Malaysian Ringgit', from: '2005-04-01' },
  NOK: { symbol: 'kr', name: 'Norwegian Krone' },
  NZD: { symbol: '$', name: 'New Zealand Dollar' },
  PHP: { symbol: '₱', name: 'Philippine Peso', from: '2005-04-01' },
  PLN: { symbol: 'zł', name: 'Polish Złoty' },
  RON: { symbol: 'lei', name: 'Romanian New Leu', from: '2005-07-01' },
  RUB: { symbol: '₽', name: 'Russian Ruble', from: '2005-04-01' },
  SEK: { symbol: 'kr', name: 'Swedish Krona' },
  SGD: { symbol: '$', name: 'Singapore Dollar' },
  THB: { symbol: '฿', name: 'Thai Baht', from: '2005-04-01' },
  TRY: { symbol: 'TRY', name: 'Turkish Lira', from: '2005-01-03' },
  USD: { symbol: '$', name: 'US Dollar' },
  ZAR: { symbol: 'R', name: 'South African Rand' },
  EUR: { symbol: '€', name: 'Euro' },
  CYP: { symbol: 'CYP', name: 'Cypriot Pound', until: '2008-01-02' },
  EEK: { symbol: 'EEK', name: 'Estonian Kroon', until: '2011-01-03' },
  ISK: { symbol: 'ISK', name: 'Icelandic Krona', until: '2008-12-10' },
  LTL: { symbol: 'LTL', name: 'Lithuanian Litas', until: '2015-01-02' },
  LVL: { symbol: 'LVL', name: 'Latvian Lat', until: '2014-01-02' },
  MTL: { symbol: 'MTL', name: 'Maltese Lira', until: '2008-01-02' },
  ROL: { symbol: 'ROL', name: 'Romanian Leu', until: '2005-07-01' },
  SIT: { symbol: 'SIT', name: 'Slovenian Tolar', until: '2007-01-02' },
  SKK: { symbol: 'Sk', name: 'Slovak Koruna', until: '2009-01-02' },
  TRL: { symbol: 'TRL', name: 'Turkish Lira (old)', until: '2005-01-02' }
}
