export const currencies = {
  GBP: { symbol: '£', name: 'British Pound' },
  AUD: { symbol: '$', name: 'Australian Dollar' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev', from: 20000719 },
  BRL: { symbol: 'R$', name: 'Brazilian Real', from: 20080102 },
  CAD: { symbol: '$', name: 'Canadian Dollar' },
  CHF: { symbol: 'Fr', name: 'Swiss Franc' },
  CNY: { symbol: '¥', name: 'Chinese Yuan Renminbi', from: 20050401 },
  CZK: { symbol: 'Kč', name: 'Czech Republic Koruna' },
  DKK: { symbol: 'kr', name: 'Danish Krone' },
  HKD: { symbol: '$', name: 'Hong Kong Dollar' },
  HRK: { symbol: 'kn', name: 'Croatian Kuna', from: 20050401 },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah', from: 20050401 },
  ILS: { symbol: '₪', name: 'Israeli New Shekel', from: 20110103 },
  INR: { symbol: '₹', name: 'Indian Rupee', from: 20090102 },
  JPY: { symbol: '¥', name: 'Japanese Yen' },
  KRW: { symbol: '₩', name: 'South Korean Won' },
  MXN: { symbol: '$', name: 'Mexican Peso', from: 20080102 },
  MYR: { symbol: 'RM', name: 'Malaysian Ringgit', from: 20050401 },
  NOK: { symbol: 'kr', name: 'Norwegian Krone' },
  NZD: { symbol: '$', name: 'New Zealand Dollar' },
  PHP: { symbol: '₱', name: 'Philippine Peso', from: 20050401 },
  PLN: { symbol: 'zł', name: 'Polish Złoty' },
  RON: { symbol: 'lei', name: 'Romanian New Leu', from: 20050701 },
  RUB: { symbol: '₽', name: 'Russian Ruble', from: 20050401 },
  SEK: { symbol: 'kr', name: 'Swedish Krona' },
  SGD: { symbol: '$', name: 'Singapore Dollar' },
  THB: { symbol: '฿', name: 'Thai Baht', from: 20050401 },
  TRY: { symbol: 'TRY', name: 'Turkish Lira', from: 20050103 },
  USD: { symbol: '$', name: 'US Dollar' },
  ZAR: { symbol: 'R', name: 'South African Rand' },
  EUR: { symbol: '€', name: 'Euro' },
  CYP: { symbol: 'CYP', name: 'Cypriot Pound', until: 20080102 },
  EEK: { symbol: 'EEK', name: 'Estonian Kroon', until: 20110103 },
  ISK: { symbol: 'ISK', name: 'Icelandic Krona', until: 20081210 },
  LTL: { symbol: 'LTL', name: 'Lithuanian Litas', until: 20150102 },
  LVL: { symbol: 'LVL', name: 'Latvian Lat', until: 20140102 },
  MTL: { symbol: 'MTL', name: 'Maltese Lira', until: 20080102 },
  ROL: { symbol: 'ROL', name: 'Romanian Leu', until: 20050701 },
  SIT: { symbol: 'SIT', name: 'Slovenian Tolar', until: 20070102 },
  SKK: { symbol: 'Sk', name: 'Slovak Koruna', until: 20090102 },
  TRL: { symbol: 'TRL', name: 'Turkish Lira', until: 20050102 }
}
